### ISSUE TITLE
JDMP.java exception

### ISSUE THREAD

**Issue by zhufengweihai** [jdmp/java-data-mining-package#4]
Uncaught error fetching image:
java.lang.NullPointerException
	at sun.awt.image.URLImageSource.getConnection(Unknown Source)
	at sun.awt.image.URLImageSource.getDecoder(Unknown Source)
	at sun.awt.image.InputStreamImageSource.doFetch(Unknown Source)
	at sun.awt.image.ImageFetcher.fetchloop(Unknown Source)
	at sun.awt.image.ImageFetcher.run(Unknown Source)

How to fix it?Thanks.

**Comment by ayushtucknat** [comment]
@zhufengweihai  can you please share your fragment of the code for better understanding of the issue.
although just by the given stack trace, the issue may persist because of the file separators. try using System.getProperty("file.separator")  while building the file path.
